#!/usr/bin/python3
from enum import Enum
import re

class Database:

    def __init__(self):
        self.keywords = [
            "create",
            "primary",
            "foreign"
        ]
        self.tables = []

        # Parse function. Expects list of lines in an array.
    def parse(self, content):
        line_num = 0
        while(line_num < len(content)):
            handle = self.handle_line(content[line_num])
            if(handle == Handle.table):
                line_num = line_num + self.parse_table(content[line_num:])

    def parse_table(self, content):
        keywords = [
            "PK",
            "FK"
        ]
        line_num = 0
        creation_tokens = content[line_num].split()
        new_table = Table(creation_tokens[2])
        line_num = line_num + 1
        while(line_num < len(content)):
            current_line = content[line_num]
            column_info = self.parse_table_line(current_line)
            if(column_info['type'] not in keywords and column_info['name']):
                new_table.add_column(
                    column_info['name'],
                    column_info['type'],
                    column_info['flags']
                )
            elif (column_info['type'] == "PK"):
                new_table.add_primary_key(column_info['name'])
            elif (column_info['type'] == "FK"):
                new_table.add_foreign_key(
                    column_info['name'],
                    column_info['fk_table'],
                    column_info['fk_reference']
                )
                pass
            line_num = line_num + 1
            if(column_info['end']):
                break
        self.tables.append(new_table)
        return line_num

    def handle_foreign_key(self, line):
        table = None
        reference = None
        if(line[2] == "("):
            table = line[3]
            line = line[5:]
        else:
            table = line[2][1:-1]
            line = line[3:]
        variableList = re.findall("[a-zA-Z]+", line[1])
        if(len(variableList) > 1):
            table = variableList[0]
            reference = variableList[1]
        else:
            if(re.match("[a-zA-Z]+\(",variableList[0])):
                table = re.match.group()[0:-1]
                reference = line[2]
            else:
                table = variableList[0]
                reference = line[3]
        return {"table": table, "reference": reference}

    def parse_flags(self, line):
        flags = []
        while(line):
            popped = line.pop(0)
            if(popped.lower() == "not"):
                next_token = line.pop(0).replace(",","")
                flags.append(popped + " " + next_token)
            else:
                popped = popped.replace(",","")
                flags.append(popped)
        return flags

    def parse_table_line(self, line):
        tokens = line.split()
        name = None
        type = None
        flags = []
        reference = None
        table = None
        table_end = True if (");" in tokens) else False
        handle = self.handle_line(line)
        if(len(tokens) > 1):
            if (handle == Handle.primary_key):
                if(tokens[2] == "("):
                    name = tokens[3]
                else:
                    #strips parentheses (string from pos 1 to pos length-1)
                    name = tokens[2][1:-1]
                type = "PK"
            elif(handle == Handle.foreign_key):
                if(tokens[2] == "("):
                    name = tokens[3]
                else:
                    name = tokens[2][1:-1]
                foreign_key_variables = self.handle_foreign_key(tokens)
                reference = foreign_key_variables["reference"]
                table = foreign_key_variables["table"]
                type = "FK"
                pass
            else:
                name = tokens[0]
                if("(" in tokens[1]):
                    type = tokens[1] + tokens[2] + tokens[3]
                    tokens = tokens[4:]
                else:
                    type = tokens[1]
                    tokens = tokens[2:]
                flags = self.parse_flags(tokens)
        return {
            "name": name,
            "type": type,
            "end": table_end,
            "flags": flags,
            "fk_reference": reference,
            "fk_table": table
        }

    def keyword_handler(self, tokens):
        if (tokens[0].lower() == "create"):
            return Handle.table
        if (tokens[0].lower() == "primary"):
            return Handle.primary_key
        if (tokens[0].lower() == "foreign"):
            return Handle.foreign_key


    # Parses 1 line of code. Expects one string.
    def handle_line(self, line):
        current_token = 0
        tokens = line.split()
        if (tokens[current_token].lower() in self.keywords):
            return self.keyword_handler(tokens)
        return Handle.none

    def import_file(self, import_file):
        file = open(import_file)
        content = file.read()
        content_lines = content.split("\n")
        content_lines = [line for line in content_lines if line.strip()]
        self.parse(content_lines)

    def export_database(self):
        tables = self.tables
        returnString = "";
        for table in tables:
            returnString += "CREATE TABLE "+table.table_name+"\n"
            for column in table.columns:
                returnString += "  "+column['name']+" "+column['type']
                for flag in column['flags']:
                    returnString+= " "+flag
                returnString += ",\n"
            for foreign_key in table.foreign_keys:
                returnString += "  FOREIGN KEY "+foreign_key['name']+" "
                returnString += "REFERENCES "+foreign_key['table']+"( "
                returnString += foreign_key['column']+" ),\n"
            returnString += "  PRIMARY KEY ( "+table.primary_key+" )\n"
            returnString += ");\n\n"
        return returnString

    def tables(self):
        return self.tables

class Handle(Enum):
    none = 100
    table = 200
    table_end = 201
    primary_key = 210
    foreign_key = 220

class Table:

    def __init__(self, table_name):
        self.table_name = table_name
        self.columns = []
        self.primary_key = ""
        self.foreign_keys = []

    def add_column(self, name, type, flags):
        if not (flags):
            self.columns.append({"name": name, "type": type})
        else:
            self.columns.append({"name": name, "type": type, "flags": flags})

    def add_primary_key(self, name):
        self.primary_key = name

    def add_foreign_key(self, name, references_table, references_column):
        self.foreign_keys.append({
            "name": name,
            "table": references_table,
            "column": references_column
        })

    def columns(self):
        return self.columns

    def foreign_keys(self):
        return self.foreign_keys

    def table_name(self):
        return self.table_name

if __name__ == "__main__":
    database = Database()
    database.import_file("test.sql")
    print(database.export_database())

