CREATE TABLE test(
	id INT NOT NULL AUTO_INCREMENT,
	name CHAR( 30 ) NOT NULL,
	PRIMARY KEY ( id, name)
);

CREATE TABLE memes(
	id INT NOT NULL AUTO_INCREMENT,
	dank CHAR( 50 ) NOT NULL,
	t_name CHAR( 30 ) NOT NULL,
	PRIMARY KEY ( id ),
	FOREIGN KEY ( t_name ) REFERENCES test(name)
);
