CREATE TABLE test(
	id INT NOT NULL AUTO_INCREMENT,
	name CHAR( 30 ) NOT NULL,
	PRIMARY KEY ( id )
);

CREATE TABLE memes(
	id INT NOT NULL AUTO_INCREMENT,
	dank CHAR( 50 ) NOT NULL,
	PRIMARY KEY ( id )
);
